version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/portal-v2"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
