import { createAdminClient } from "@/lib/supabase/admin";
import { formatCurrency } from "@/lib/utils/format";

export type FinanceHandoffStatus =
  | "pending"
  | "draft_ready"
  | "sent"
  | "failed";

export type FinanceHandoff = {
  id: string;
  invoiceId: string;
  campaignVendorId: string;
  campaignId: string | null;
  vendorId: string | null;
  hopApprovedBy: string | null;
  hopApprovedAt: string | null;
  status: FinanceHandoffStatus;
  attemptCount: number;
  lastAttemptAt: string | null;
  lastError: string;
  emailTo: string[];
  emailCc: string[];
  emailSubject: string;
  emailBody: string;
  summary: Record<string, unknown>;
  campaignName: string | null;
  wfNumber: string | null;
  vendorName: string | null;
  createdAt: string;
  updatedAt: string;
};

export type FinanceHandoffDraftInput = {
  wfNumber: string;
  campaignName: string;
  vendorName: string;
  vendorContact: string;
  vendorEmail: string;
  poNumber: string;
  estimateTotal: number;
  invoiceTotal: number;
  variance: number;
  invoiceFileName: string;
  invoiceFileUrl: string | null;
  submittedAt: string | null;
  producerApprovedAt: string | null;
  hopApprovedAt: string | null;
  lineItems: Array<{
    description: string;
    amount: number;
  }>;
};

function getSingleRelationRow(
  value:
    | Record<string, unknown>
    | Record<string, unknown>[]
    | null
    | undefined
): Record<string, unknown> | null {
  if (!value) return null;
  return Array.isArray(value) ? value[0] ?? null : value;
}

function parseEmailList(raw: string | undefined): string[] {
  if (!raw) return [];
  return raw
    .split(",")
    .map((email) => email.trim())
    .filter((email) => email.length > 0);
}

function formatDateTime(value: string | null): string {
  if (!value) return "N/A";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export function buildFinanceEmailDraft(
  input: FinanceHandoffDraftInput,
  options?: {
    to?: string[];
    cc?: string[];
  }
): {
  to: string[];
  cc: string[];
  subject: string;
  body: string;
  summary: Record<string, unknown>;
} {
  const to = options?.to ?? [];
  const cc = options?.cc ?? [];
  const subject = `[Finance Handoff] ${input.wfNumber} ${input.campaignName} · ${input.vendorName}`;
  const lineItemsSection =
    input.lineItems.length === 0
      ? "- No parsed line items available."
      : input.lineItems
          .map((item) => `- ${item.description}: ${formatCurrency(item.amount)}`)
          .join("\n");

  const body = [
    "Finance Team,",
    "",
    "Please process the approved vendor invoice using the details below.",
    "",
    `Campaign: ${input.wfNumber} - ${input.campaignName}`,
    `Vendor: ${input.vendorName}`,
    `Vendor Contact: ${input.vendorContact}`,
    `Vendor Email: ${input.vendorEmail}`,
    `PO Number: ${input.poNumber}`,
    `Estimate Total: ${formatCurrency(input.estimateTotal)}`,
    `Invoice Total: ${formatCurrency(input.invoiceTotal)}`,
    `Variance: ${formatCurrency(input.variance)}`,
    `Invoice File: ${input.invoiceFileName}`,
    `Invoice URL: ${input.invoiceFileUrl || "N/A"}`,
    "",
    "Approval Trail",
    `- Submitted: ${formatDateTime(input.submittedAt)}`,
    `- Producer Approved: ${formatDateTime(input.producerApprovedAt)}`,
    `- HOP Approved: ${formatDateTime(input.hopApprovedAt)}`,
    "",
    "Parsed Line Items",
    lineItemsSection,
    "",
    "Generated by Portal workflow automation.",
  ].join("\n");

  return {
    to,
    cc,
    subject,
    body,
    summary: {
      wfNumber: input.wfNumber,
      campaignName: input.campaignName,
      vendorName: input.vendorName,
      vendorContact: input.vendorContact,
      vendorEmail: input.vendorEmail,
      poNumber: input.poNumber,
      estimateTotal: input.estimateTotal,
      invoiceTotal: input.invoiceTotal,
      variance: input.variance,
      invoiceFileName: input.invoiceFileName,
      invoiceFileUrl: input.invoiceFileUrl,
      submittedAt: input.submittedAt,
      producerApprovedAt: input.producerApprovedAt,
      hopApprovedAt: input.hopApprovedAt,
      lineItems: input.lineItems,
      generatedAt: new Date().toISOString(),
    },
  };
}

function toFinanceHandoff(row: Record<string, unknown>): FinanceHandoff {
  const campaign = getSingleRelationRow(
    row.campaigns as Record<string, unknown> | Record<string, unknown>[] | null
  );
  const vendor = getSingleRelationRow(
    row.vendors as Record<string, unknown> | Record<string, unknown>[] | null
  );

  return {
    id: row.id as string,
    invoiceId: row.invoice_id as string,
    campaignVendorId: row.campaign_vendor_id as string,
    campaignId: (row.campaign_id as string) || null,
    vendorId: (row.vendor_id as string) || null,
    hopApprovedBy: (row.hop_approved_by as string) || null,
    hopApprovedAt: (row.hop_approved_at as string) || null,
    status: row.status as FinanceHandoffStatus,
    attemptCount: Number(row.attempt_count) || 0,
    lastAttemptAt: (row.last_attempt_at as string) || null,
    lastError: (row.last_error as string) || "",
    emailTo: (row.email_to as string[] | null) || [],
    emailCc: (row.email_cc as string[] | null) || [],
    emailSubject: (row.email_subject as string) || "",
    emailBody: (row.email_body as string) || "",
    summary: (row.summary as Record<string, unknown>) || {},
    campaignName: (campaign?.name as string | undefined) || null,
    wfNumber: (campaign?.wf_number as string | undefined) || null,
    vendorName: (vendor?.company_name as string | undefined) || null,
    createdAt: row.created_at as string,
    updatedAt: row.updated_at as string,
  };
}

export async function createOrUpdateFinanceHandoff(input: {
  invoiceId: string;
  campaignVendorId: string;
  hopApprovedBy: string | null;
}): Promise<FinanceHandoff> {
  const db = createAdminClient();

  const { data: invoice, error: invoiceError } = await db
    .from("vendor_invoices")
    .select(
      "id, campaign_vendor_id, file_name, file_url, submitted_at, producer_approved_at, hop_approved_at"
    )
    .eq("id", input.invoiceId)
    .maybeSingle();
  if (invoiceError) throw invoiceError;
  if (!invoice) throw new Error("Invoice not found for finance handoff");
  if (invoice.campaign_vendor_id !== input.campaignVendorId) {
    throw new Error("Invoice/campaign vendor mismatch for finance handoff");
  }

  const { data: assignment, error: assignmentError } = await db
    .from("campaign_vendors")
    .select(
      "id, campaign_id, vendor_id, po_number, estimate_total, invoice_total, campaigns(name, wf_number, producer_id), vendors(company_name, contact_name, email)"
    )
    .eq("id", input.campaignVendorId)
    .maybeSingle();
  if (assignmentError) throw assignmentError;
  if (!assignment) throw new Error("Campaign vendor assignment not found");

  const campaign = getSingleRelationRow(
    assignment.campaigns as
      | Record<string, unknown>
      | Record<string, unknown>[]
      | null
  );
  const vendor = getSingleRelationRow(
    assignment.vendors as
      | Record<string, unknown>
      | Record<string, unknown>[]
      | null
  );

  const { data: invoiceItems, error: itemsError } = await db
    .from("vendor_invoice_items")
    .select("description, amount")
    .eq("invoice_id", input.invoiceId)
    .order("sort_order", { ascending: true });
  if (itemsError) throw itemsError;

  const producerId =
    (campaign?.producer_id as string | undefined) || null;
  const userIds = [producerId, input.hopApprovedBy].filter(
    (value): value is string => Boolean(value)
  );

  const emailByUserId = new Map<string, string>();
  if (userIds.length > 0) {
    const { data: users, error: usersError } = await db
      .from("users")
      .select("id, email")
      .in("id", userIds);
    if (usersError) throw usersError;
    for (const row of users || []) {
      if (row.id && row.email) {
        emailByUserId.set(row.id, row.email);
      }
    }
  }

  const configuredTo = parseEmailList(process.env.FINANCE_HANDOFF_TO);
  const configuredCc = parseEmailList(process.env.FINANCE_HANDOFF_CC);
  const to = configuredTo.length > 0 ? configuredTo : ["finance@company.com"];
  const cc = [
    ...configuredCc,
    producerId ? emailByUserId.get(producerId) || null : null,
    input.hopApprovedBy ? emailByUserId.get(input.hopApprovedBy) || null : null,
  ]
    .filter((email): email is string => Boolean(email))
    .filter((email, index, all) => all.indexOf(email) === index)
    .filter((email) => !to.includes(email));

  const estimateTotal = Number(assignment.estimate_total || 0);
  const invoiceTotal = Number(assignment.invoice_total || 0);
  const variance = invoiceTotal - estimateTotal;
  const wfNumber = (campaign?.wf_number as string | undefined) || "WF";

  const draft = buildFinanceEmailDraft(
    {
      wfNumber,
      campaignName: (campaign?.name as string | undefined) || "Campaign",
      vendorName: (vendor?.company_name as string | undefined) || "Vendor",
      vendorContact: (vendor?.contact_name as string | undefined) || "N/A",
      vendorEmail: (vendor?.email as string | undefined) || "N/A",
      poNumber:
        (assignment.po_number as string | null) || `PO-${wfNumber}`,
      estimateTotal,
      invoiceTotal,
      variance,
      invoiceFileName: (invoice.file_name as string) || "Invoice",
      invoiceFileUrl: (invoice.file_url as string) || null,
      submittedAt: (invoice.submitted_at as string) || null,
      producerApprovedAt: (invoice.producer_approved_at as string) || null,
      hopApprovedAt: (invoice.hop_approved_at as string) || null,
      lineItems: (invoiceItems || []).map((row) => ({
        description: (row.description as string) || "Line item",
        amount: Number(row.amount) || 0,
      })),
    },
    { to, cc }
  );

  const { data: existing, error: existingError } = await db
    .from("finance_handoffs")
    .select("id, attempt_count")
    .eq("invoice_id", input.invoiceId)
    .maybeSingle();
  if (existingError) throw existingError;

  const attemptCount = Number(existing?.attempt_count || 0) + 1;
  const now = new Date().toISOString();

  const { data: saved, error: saveError } = await db
    .from("finance_handoffs")
    .upsert(
      {
        invoice_id: input.invoiceId,
        campaign_vendor_id: input.campaignVendorId,
        campaign_id: assignment.campaign_id,
        vendor_id: assignment.vendor_id,
        hop_approved_by: input.hopApprovedBy,
        hop_approved_at: invoice.hop_approved_at || null,
        status: "draft_ready",
        attempt_count: attemptCount,
        last_attempt_at: now,
        last_error: "",
        email_to: draft.to,
        email_cc: draft.cc,
        email_subject: draft.subject,
        email_body: draft.body,
        summary: draft.summary,
      },
      { onConflict: "invoice_id" }
    )
    .select("*, campaigns(name, wf_number), vendors(company_name)")
    .single();
  if (saveError) throw saveError;

  return toFinanceHandoff(saved as Record<string, unknown>);
}

export async function recordFinanceHandoffFailure(input: {
  invoiceId: string;
  campaignVendorId: string;
  hopApprovedBy: string | null;
  errorMessage: string;
}): Promise<FinanceHandoff> {
  const db = createAdminClient();

  const { data: existing, error: existingError } = await db
    .from("finance_handoffs")
    .select("attempt_count")
    .eq("invoice_id", input.invoiceId)
    .maybeSingle();
  if (existingError) throw existingError;

  const attemptCount = Number(existing?.attempt_count || 0) + 1;
  const now = new Date().toISOString();

  const { data: saved, error: saveError } = await db
    .from("finance_handoffs")
    .upsert(
      {
        invoice_id: input.invoiceId,
        campaign_vendor_id: input.campaignVendorId,
        hop_approved_by: input.hopApprovedBy,
        status: "failed",
        attempt_count: attemptCount,
        last_attempt_at: now,
        last_error: input.errorMessage,
      },
      { onConflict: "invoice_id" }
    )
    .select("*, campaigns(name, wf_number), vendors(company_name)")
    .single();
  if (saveError) throw saveError;

  return toFinanceHandoff(saved as Record<string, unknown>);
}

export async function listFinanceHandoffs(filters?: {
  status?: FinanceHandoffStatus;
  campaignIds?: string[];
}): Promise<FinanceHandoff[]> {
  const db = createAdminClient();
  let query = db
    .from("finance_handoffs")
    .select("*, campaigns(name, wf_number), vendors(company_name)")
    .order("created_at", { ascending: false });

  if (filters?.status) {
    query = query.eq("status", filters.status);
  }

  if (filters?.campaignIds && filters.campaignIds.length > 0) {
    query = query.in("campaign_id", filters.campaignIds);
  }

  const { data, error } = await query;
  if (error) throw error;
  return (data || []).map((row) =>
    toFinanceHandoff(row as Record<string, unknown>)
  );
}

export async function retryFinanceHandoffById(
  handoffId: string
): Promise<FinanceHandoff> {
  const db = createAdminClient();
  const { data: handoff, error } = await db
    .from("finance_handoffs")
    .select("id, invoice_id, campaign_vendor_id, hop_approved_by")
    .eq("id", handoffId)
    .maybeSingle();
  if (error) throw error;
  if (!handoff) throw new Error("Finance handoff not found");

  return createOrUpdateFinanceHandoff({
    invoiceId: handoff.invoice_id,
    campaignVendorId: handoff.campaign_vendor_id,
    hopApprovedBy: handoff.hop_approved_by || null,
  });
}
